FROM python:3.12-slim as py3.12
WORKDIR /app

# Install necessary system packages
RUN apt-get update && apt-get install -y \
    gcc \
    make \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy application files
COPY newtype/ ./newtype/
COPY tests/ ./tests/
COPY build.py ./
COPY Makefile ./
COPY README.md ./
COPY pyproject.toml ./

RUN python -m venv .venv && \
    export PATH=".venv/bin:$PATH" && \
    make install-test VERSION=3.12 && \
    deactivate

FROM python:3.12-slim as py3.12

# Change to the client directory
WORKDIR /client

# Install necessary system packages
RUN apt-get update && apt-get install -y \
    gcc \
    make \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy the distribution files and example script
COPY dist/ ./dist/
COPY tests/ ./
COPY Makefile ./
COPY examples/demo.py ./

# Install the package from the distribution
RUN python -m venv .venv && \
    . .venv/bin/activate && \
    python -m pip install dist/*.tar.gz && \
    python -c "from newtype import NewType" && \
    python -m demo && \
    python -m pip install pytest && \
    python -m pip install pandas && \
    make test && \
    deactivate

# Set the default command to execute when the container starts
CMD ["echo", "all tests done"]
